language: node_js
services:
  - postgresql
node_js:
  - '8'
  - '11'
before_script:
  - psql -c 'create database moi_test;' -U postgres
script:
  - npm i && npm run build && npm test
env:
  - PGUSER = postgres
  - PGDATABASE = moi_test
